name: ci

on:
  pull_request:
    branches:
      - main
      - prerelease
  push:
    branches:
      - main

jobs:
  rust:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # mysql 
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: mysql
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_ROOT_PASSWORD: mysql
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true

      - name: Install tools
        run: |
          apt-get update
          apt-get install -y curl postgresql-client build-essential pkg-config libssl-dev git sqlite3 libsqlite3-dev mysql-client
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-05-30
          components: rustfmt
          default: true

      - name: Install other dependent tools
        run: |
          cargo install just

      - name: Is the code formatted?
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check -q

      - name: Seed the database
        run: just seed-db
        env:
          POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
          SQLITE_URL: "sqlite:///tmp/test.db"
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DB: mysql
          MYSQL_USER: root
          MYSQL_PASSWORD: mysql


      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
          SQLITE_URL: "sqlite:///tmp/test.db"
          MYSQL_URL: "mysql://root:mysql@localhost:3306/mysql"

      - name: Test build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

  python:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # mysql 
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: mysql
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_ROOT_PASSWORD: mysql
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true

      - name: Install tools
        run: |
          apt-get update
          apt-get install -y curl postgresql-client build-essential python3-dev python3-pip pkg-config libssl-dev git sqlite3 libsqlite3-dev mysql-client
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-05-30
          components: rustfmt
          default: true

      - name: Install other dependent tools
        run: |
          pip3 install poetry
          cargo install just

      - name: Install python dependencies
        run: just bootstrap-python

      - name: Seed the database
        run: just seed-db
        env:
          POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
          SQLITE_URL: "sqlite:///tmp/test.db"
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DB: tpch
          MYSQL_USER: root
          MYSQL_PASSWORD: mysql


      - name: Test python
        run: just test-python
        env:
          POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
          SQLITE_URL: "sqlite:///tmp/test.db"
          MYSQL_URL: "mysql://root:mysql@localhost:3306/mysql"
